AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an S3 bucket and a role to access said bucket.
Parameters:
  ClusterBucketName:
    Description: Name of the S3bucket you want to create.
    Type: String
  IAMRoleName:
    Description: Name of the IAM role to be used to access the S3 bucket.
    Type: String
Resources:
  ClusterBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref ClusterBucketName
  ClusterBucketIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  RolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: ClusterBucketAccess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'describe'
            Resource:
            - !Join ['', ['arn:aws:s3:::', !Ref 'ClusterBucket', /*]]
      Roles:
        - !Ref ClusterBucketIAMRole
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ClusterBucketIAMRole
